### ISSUE TITLE
[TODO] General

### ISSUE THREAD

**Issue by daftspunk** [rainlab/blog-plugin#83]
#### Features
- [x] RSS feed https://github.com/octobercms/october/issues/449
- [ ] Markdown / Rich editor modes
- [x] Media manager implemented in Markdown editor
- [ ] Snippets support, for example, code blocks
- [x] Nested categories
- [x] Read more functionality #74
- [ ] Make excerpt optional with a checkbox, take a sample from the content otherwise
- [ ] Searching #101

**Comment by scottbedard** [comment]
Nice, rich editor mode will be awesome for clients that don't understand markdown!

**Comment by bennothommo** [comment]
@daftspunk @LukeTowers Is there anything in this list that you still wanted implemented? Given it was started 4 years ago, it might be a bit out-of-date now :)

Search is already covered by [this plugin](https://octobercms.com/plugin/offline-sitesearch), for example.

**Comment by w20k** [comment]
@bennothommo maybe you could update the list:)?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
